// Generated by CoffeeScript 1.6.3
var ArcherCtrl;

ArcherCtrl = function($scope) {
  $scope.archers = [
    {
      name: 'ArcherA',
      sets: [],
      total: 0
    }, {
      name: 'ArcherB',
      sets: [],
      total: 0
    }, {
      name: 'ArcherC',
      sets: [],
      total: 0
    }, {
      name: 'ArcherD',
      sets: [],
      total: 0
    }, {
      name: 'ArcherE',
      sets: [],
      total: 0
    }
  ];
  $scope.activeArcher = '';
  $scope.new_set_values = '';
  $scope.countShots = function(set) {
    var total;
    total = 0;
    set.forEach(function(shot) {
      return total += parseInt(shot, 10);
    });
    return total;
  };
  $scope.updateActiveArcher = function(archerName) {
    $scope.activeArcher = archerName;
    console.log("updating active archer: " + archerName);
    return console.log("now set to: " + $scope.activeArcher);
  };
  return $scope.addSet = function() {
    if ($scope.activeArcher === '') {
      alert("Please select archer first");
    }
    return $scope.archers.forEach(function(archer) {
      var new_set;
      console.log('testing: ' + archer.name);
      if (archer.name === $scope.activeArcher) {
        console.log("found him");
        console.log("Adding set: " + $scope.new_set_values);
        new_set = $scope.new_set_values.split(' ');
        archer.sets.push(new_set);
        console.log(archer.sets);
        return new_set.forEach(function(shot) {
          return archer.total += parseInt(shot, 10);
        });
      }
    });
  };
};
