// Generated by CoffeeScript 1.6.3
var Archer, ArcherCtrl, Set;

Set = (function() {
  Set.shots;

  Set.total;

  function Set() {
    this.shots = [];
    this.total = 0;
  }

  return Set;

})();

Archer = (function() {
  var currentSet;

  Archer.sets;

  Archer.total;

  Archer.averageSet;

  Archer.name;

  currentSet = new Set();

  function Archer(_name) {
    if (_name == null) {
      _name = '';
    }
    this.name = _name;
    this.sets = [new Set()];
    this.total = 0;
    this.averageSet = 0;
    currentSet = this.sets[this.sets.length - 1];
  }

  Archer.prototype.addShot = function(value) {
    console.log("adding " + value);
    currentSet.shots.push(value);
    currentSet.total += value;
    return this.total += value;
  };

  Archer.prototype.finishSet = function() {
    this.sets.push(new Set());
    currentSet = this.sets[this.sets.length - 1];
    return this.averageSet = (this.total / (this.sets.length - 1)).toFixed(1);
  };

  return Archer;

})();

ArcherCtrl = function($scope) {
  $scope.archers = [new Archer('ArcherA')];
  $scope.activeArcher = $scope.archers[0];
  $scope.menuStatus = '';
  $scope.toggleMenu = function() {
    if ($scope.menuStatus === '') {
      return $scope.menuStatus = 'open';
    } else {
      return $scope.menuStatus = '';
    }
  };
  $scope.updateActiveArcher = function(archerIndex) {
    $scope.activeArcher = $scope.archers[archerIndex];
    console.log("archer set to: " + $scope.activeArcher.name);
    return $scope.menuStatus = '';
  };
  $scope.newArcher = function() {
    var name;
    name = prompt("Name of archer?");
    $scope.archers.push(new Archer(name));
    return console.log("added new archer: " + name);
  };
  $scope.addShot = function(value) {
    return $scope.activeArcher.addShot(value);
  };
  $scope.finishSet = function() {
    return $scope.activeArcher.finishSet();
  };
  return $scope.rename = function() {
    return $scope.activeArcher.name = prompt("Enter new name");
  };
};
